services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: incident_hub
      MYSQL_USER: incident_hub
      MYSQL_PASSWORD: incident_hub_secret
      MYSQL_ROOT_PASSWORD: incident_hub_root_secret
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pincident_hub_root_secret"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      APP_NAME: Incident Hub
      APP_ENV: local
      APP_KEY: base64:BreR6Kjd1DjrChQqzHMVgIH7DMsHD6iitjopfqaAMe8=
      APP_DEBUG: "false"
      APP_URL: http://localhost:8000
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: incident_hub
      DB_USERNAME: incident_hub
      DB_PASSWORD: incident_hub_secret
    ports:
      - "8000:8000"
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  mysql_data:
